banned_terms:
  - "api.headysystems.com"
  - "api.headysystems.com"
  - "0.0.0.0"
allowed_domains:
  - "headyio.com"
  - "headymcp.com"
  - "headybuddy.org"
  - "headyconnection.org"
  - "headysystems.com"
  - "headyed.com"
